#!/bin/bash
# Regenerate all code from regs/cmod7_regs.yaml.
# Run from the project root: ./regs/generate.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
YAML="$SCRIPT_DIR/cmod7_regs.yaml"
TMPL="$SCRIPT_DIR/templates/common"

mkdir -p "$PROJECT_DIR/src/gen" "$PROJECT_DIR/tools/gen"

# Elaborate YAML to IR (pass -i to override the default 'blocks/' include search)
IR=$(regio-elaborate -f block -i "$SCRIPT_DIR" "$YAML")

# Verilog-2001 register storage module + address defines
echo "$IR" | regio-generate -f block -g sv -t "$TMPL" -o "$PROJECT_DIR/src/gen" -
mv "$PROJECT_DIR/src/gen/cmod7_reg_blk.sv" "$PROJECT_DIR/src/gen/cmod7_reg_store.sv"

# Python register definitions
echo "$IR" | regio-generate -f block -g py -t "$TMPL" -o "$PROJECT_DIR/tools/gen" -

# Package marker (not generated by regio)
touch "$PROJECT_DIR/tools/gen/__init__.py"

echo "reggen: generated files written to src/gen/ and tools/gen/"
